/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rwge_graphics_TextureData */

#ifndef _Included_rwge_graphics_TextureData
#define _Included_rwge_graphics_TextureData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rwge_graphics_TextureData
 * Method:    intArraytoByteBuffer
 * Signature: ([II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_rwge_graphics_TextureData_intArraytoByteBuffer
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
