/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rwge_math_Matrix4 */

#ifndef _Included_rwge_math_Matrix4
#define _Included_rwge_math_Matrix4
#ifdef __cplusplus
extern "C" {
#endif
#undef rwge_math_Matrix4_serialVersionUID
#define rwge_math_Matrix4_serialVersionUID 7570678718655565027i64
#undef rwge_math_Matrix4_M00
#define rwge_math_Matrix4_M00 0L
#undef rwge_math_Matrix4_M01
#define rwge_math_Matrix4_M01 4L
#undef rwge_math_Matrix4_M02
#define rwge_math_Matrix4_M02 8L
#undef rwge_math_Matrix4_M03
#define rwge_math_Matrix4_M03 12L
#undef rwge_math_Matrix4_M10
#define rwge_math_Matrix4_M10 1L
#undef rwge_math_Matrix4_M11
#define rwge_math_Matrix4_M11 5L
#undef rwge_math_Matrix4_M12
#define rwge_math_Matrix4_M12 9L
#undef rwge_math_Matrix4_M13
#define rwge_math_Matrix4_M13 13L
#undef rwge_math_Matrix4_M20
#define rwge_math_Matrix4_M20 2L
#undef rwge_math_Matrix4_M21
#define rwge_math_Matrix4_M21 6L
#undef rwge_math_Matrix4_M22
#define rwge_math_Matrix4_M22 10L
#undef rwge_math_Matrix4_M23
#define rwge_math_Matrix4_M23 14L
#undef rwge_math_Matrix4_M30
#define rwge_math_Matrix4_M30 3L
#undef rwge_math_Matrix4_M31
#define rwge_math_Matrix4_M31 7L
#undef rwge_math_Matrix4_M32
#define rwge_math_Matrix4_M32 11L
#undef rwge_math_Matrix4_M33
#define rwge_math_Matrix4_M33 15L
/*
 * Class:     rwge_math_Matrix4
 * Method:    multiply
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_rwge_math_Matrix4_multiply
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
