fxc.exe	^
/T 		fx_2_0 ^
/Fo 	BaseForwardShading.shader ^
/Zi ^
/LD	^
/D		BASE_COLOR_EXPRESSION=0 ^
/D		EMISSIVE_COLOR_EXPRESSION=0 ^
/D		NORMAL_EXPRESSION=0 ^
/D		METALLIC_EXPRESSION=0 ^
/D		SPECULAR_EXPRESSION=0 ^
/D		ROUGHNESS_EXPRESSION=0 ^
/D		OPACITY_EXPRESSION=0 ^
/D		OPACITY_MASK_EXPRESSION=0 ^
/D		MATERIAL_BLEND_MODE=0 ^
/D		MATERIAL_SHADING_MODE=1 ^
/D		MATERIAL_TWO_SIDED=0 ^
/D		MATERIAL_NONMETAL=0 ^
/D		MATERIAL_FULLY_ROUGH=0 ^
/D		LIGHT_TYPE=2 ^
BaseForwardShading.hlsl

@pause